language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t broodwich87/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true broodwich87/docker-react npm run test